### ISSUE TITLE
Subclassed Errors not supported

### ISSUE THREAD

**Issue by indieisaconcept** [MarkHerhold/palin#1]
@MarkHerhold just an FYI due to the version of check-types you are using subclassed Errors are not being correctly identifed. 

check-types is now on version 5.1.0. 

I may raise a PR fixing this in the next couple of days, unless ofcource you beat me to it.

Nice module btw - only just discovered Bristol and the first thing I wanted was colored output and this module works great.

**Comment by MarkHerhold** [comment]
@indieisaconcept Thanks for the note and excellent catch!
I think you are referencing https://github.com/philbooth/check-types.js/issues/54 - I will gladly make a PR to use `check-types` v5.1.0.

**Comment by MarkHerhold** [comment]
@indieisaconcept Landed in v1.1.0

**Comment by indieisaconcept** [comment]
Awesome. Thanks will check it out

**Comment by indieisaconcept** [comment]
@MarkHerhold I can confirm this fixes my particular issue - cheers!
