### ISSUE TITLE
Timestamp inconsistencies

### ISSUE THREAD

**Issue by jeffijoe** [MarkHerhold/palin#6]
The milliseconds should be left padded - my OCD is killing me :laughing: 

![image](https://cloud.githubusercontent.com/assets/2505474/17512130/ae3bfb4e-5e26-11e6-8c31-57b2b6ccd65a.png)

**Comment by MarkHerhold** [comment]
Ha! Good find!

**Comment by jeffijoe** [comment]
I use this formatter in every project so I'm bound to find _something_ :boar:

**Comment by MarkHerhold** [comment]
Landed in 2.0.1

Thanks @jeffijoe !
